port = 8000
host = "0.0.0.0"

[database]
port = 5432
host = "127.0.0.1"
username = "postgres"
password = "postgres"
database_name = "newsletter"
require_ssl = false

[email_client]
base_url = "localhost"
sender_email = "test@mail.ru"