services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: newsletter

  zero2prod:
    image: zero2prod-ubuntu-2-layers-bookworm-slim
    environment:
      APP__PORT: 80
      APP__DATABASE__HOST: postgres
    ports:
      - 8001:80

  jaeger:
    image: jaegertracing/all-in-one
    restart: always
    container_name: jaeger
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
      - 4317:4317
      - 4318:4318
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true
